channels:
  - conda-forge
dependencies:
  - python=3.7.5
  - pip=20.1
  - nodejs=16.13.2
  - pip:
      - robotframework-browser==12.0.1
      - rpaframework[aws]==12.8.2
rccPostInstall:
  - rfbrowser init
