channels:
  - conda-forge
dependencies:
  - python=3.7.5
  - pip=20.1
  - nodejs=14.17.4
  - pip:
      - robotframework-browser==10.1.0
      - rpaframework[aws]==12.0.3
rccPostInstall:
  - rfbrowser init
