channels:
  - conda-forge
dependencies:
  - python=3.7.5
  - pip=20.1
  - nodejs=16.13.2
  - pip:
      - robotframework-browser==11.4.0
      - rpaframework[aws]==12.8.0
rccPostInstall:
  - rfbrowser init
