channels:
  - conda-forge
dependencies:
  - python=3.7.5
  - pip=20.1
  - nodejs=14.17.4
  - pip:
      - robotframework-browser==10.0.3
      - rpaframework[aws]==11.6.3
rccPostInstall:
  - rfbrowser init
